### ISSUE TITLE
Example not working with newer versions of protobuf

### ISSUE THREAD

**Issue by Panky-codes** [joshrotenberg/zmqpbexample#2]
Hey! Thanks a lot for the amazing example. However, I had to recompile my protobuf with the following command `protoc -I=. --cpp_out=src/ .zmqpbexample.proto` from the home folder for the example to work. Do you want to include it in the README or as a part of the configuration? I can create a PR if you want the former option. 

Error message fyi:
`In file included from zmqpbexample.pb.cc:5:0:
zmqpbexample.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
zmqpbexample.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
zmqpbexample.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
zmqpbexample.pb.cc:13:10: fatal error: google/protobuf/wire_format_lite_inl.h: No such file or directory
 #include <google/protobuf/wire_format_lite_inl.h>`

**Comment by joshrotenberg** [comment]
Happy to accept a PR. I've been meaning to migrate the build system over to Bazel and upgrade other parts in the process but just haven't had the time or motivation.
